---
abstract: 'Extended display identification data (EDID) parser'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.93
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-EDID
no_index:
  directory:
    - t
    - inc
requires: {}
version: v1.0.5
